### ISSUE TITLE
Don't return JSON arrays, just objects

### ISSUE THREAD

**Issue by phxql** [phxql/restwars#75]
Don't return JSON arrays, just objects to ease client code. If there is a list returned, return an object which just one property, which contains the list.

**Comment by vlow** [comment]
If I understand aright, the JSON API standard declares this as a 'MUST' (top level must be json object). Top level JSON objects can therefore be considered as best practice: http://jsonapi.org/format/#document-structure-top-level

**Comment by phxql** [comment]
This is also a prerequisite for implementing HATEOAS.

**Comment by phxql** [comment]
Implemented. This will break all older clients, sorry. The JVM restwars API has been refactored to reflect the changes.

**Comment by vlow** [comment]
Yays! Cheers mate.
