### ISSUE TITLE
Feature: Add websocket to determine the beginning of the next round

### ISSUE THREAD

**Issue by vlow** [phxql/restwars#78]
Add a websocket to the server which sends out a small ping whenever a new round begins (e.g. containing the round number). Check this delicious piece of software: https://github.com/joewalnes/websocketd

**Comment by phxql** [comment]
Done. Check this: https://github.com/phxql/restwars/blob/master/docs/webservice.md

**Comment by vlow** [comment]
Wow, nicely done! This renders a lot of bloaty synchronizing code in the clients redundant!
